In [1]:
import numpy as np

In [2]:
def read_data(file_name: str):
    with open(file_name, "r") as file:
        data = file.read()
    data = data.split(" ")
    return data


In [3]:
def oneD_arr_to_2D(data_from_file, size: int):
    matrix = np.empty(shape=[size, size], dtype=int)
    count = 0
    for i in range(size):
        for j in range(size):

            matrix[i][j] = data_from_file[count]
            count += 1
    return matrix


In [4]:
def check_result(matrix_res_python, matrix_res_c) -> bool:
    size = len(matrix_res_c[0])
    for i in range(size):
        for j in range(size):
            if (matrix_res_c != matrix_res_python).any():
                    print("Размер-", size,"*",size,"Посчитан неверно")
    print("Размер-", size,"*",size,"Посчитан верно")
    


In [5]:
data = read_data("1000.txt")
matrix = oneD_arr_to_2D(data, 1000)
matrix_12 = np.asmatrix(matrix)
print(matrix_12)


[[95 30 13 ... 39 51 69]
 [77 44 76 ... 71 30 29]
 [35 66  0 ... 33 72 82]
 ...
 [32 84 92 ...  0 67 72]
 [50 54 36 ... 52 87 95]
 [ 1 44 65 ... 50 64 10]]


In [6]:
hard_code_names = [500, 1000, 1500, 2000]
for i in hard_code_names:
    print(i)
    file_name_first = str(i) +".txt"
    file_name_second = str(i) + "_2" + ".txt"
    file_name_result = "result_" + str(i) + ".txt"
    matrix_1 = np.asmatrix(oneD_arr_to_2D(read_data(file_name_first), i))
    matrix_2 = np.asmatrix(oneD_arr_to_2D(read_data(file_name_second), i))
    matrix_res_c = np.asmatrix(oneD_arr_to_2D(read_data(file_name_result), i))
    matrix_res_python = np.matmul(matrix_1, matrix_2)
    check_result(matrix_res_python, matrix_res_c)
    
    

500
Размер- 1 * 1 Посчитан верно
1000
Размер- 1 * 1 Посчитан верно
1500
Размер- 1 * 1 Посчитан верно
2000
Размер- 1 * 1 Посчитан верно
